version: "3.9"
services: 
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: dev 
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
      POSTGRES_DB: lireddit_v0
    volumes: 
      - ./pgdata:/var/lib/data
    ports: 
      - '5432:5432'
    links: 
      - redis
  redis:
    image: redis
    ports: 
      - '6379:6379'
  web: 
    image: dylvaz/lireddit:1.0.3
    depends_on: 
      - db
      - redis
    ports: 
      - '8080:8080'
